FROM ubuntu:18.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
        libssl-dev make \
        python3-pip python3-dev \
        sudo && \
        pip3 install setuptools wheel && \
        pip3 install pylint && \
    rm -rf /var/lib/apt/lists/*
