FROM brazil-data-cube/base:0.1

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common && \
    rm -rf /var/lib/apt/lists/*

RUN add-apt-repository -y ppa:ubuntugis/ppa && \
    apt-get update && \
    apt-get install -y \
        libgdal-dev gdal-bin && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install GDAL==2.4
