FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7

RUN apk --update add bash nano git libffi-dev build-base gcc musl-dev openssl make \
        sudo && \
        pip3 install setuptools wheel && \
        pip3 install pylint && \
    rm -rf /var/lib/apt/lists/*

ENV STATIC_URL /static
ENV STATIC_PATH /var/www/app/static
